`timescale 1ns/1ps

module sys_systolic_scheduler #(parameter int N = 4)(
    input logic [$clog2(2*N+1)-1:0] cycle,
    input logic [7:0] A[N][N],
    input logic [7:0] B[N][N],
    output logic [7:0] a_out[N],
    output logic [7:0] b_out[N]
);//no clk because scheduler is gonna work on cycle basis which is generated by the controller
localparam int CYCLE_W = $clog2(2*N+1);
always_comb begin
    for (int i =0;i<N;i++) begin
        a_out[i] = '0;
        b_out[i] = '0;
        if ((cycle >=CYCLE_W'(i)) && (cycle <CYCLE_W'(i+N)))begin
            a_out[i] = A[i][int'(cycle)-i];
            b_out[i] = B[int'(cycle)-i][i];
        end
    end
end
endmodule

